### ISSUE TITLE
Incompatibility with VanillaConfig

### ISSUE THREAD

**Issue by barcedev** [Tre5et/ridehud#3]
I get this error when booting RideHud with VanillaConfig. 
![image](https://github.com/Tre5et/ridehud/assets/20468242/0614c82d-e6a4-41df-95e3-267ba5cba2ac)

Seems like RideHud is asking for a version of VanillaConfig that doesn't exist.

**Comment by Tre5et** [comment]
Thanks for reporting!

You are correct, this is a wrong version declaration that happened because of some confusion with development version naming of VanillaConfig.

This has been fixed in the latest release (v1.3.2), which you can now get on Modrinth (it's still being approved on CurseForge).
