### ISSUE TITLE
Overlaps armor bar when health is abvoe 20.

### ISSUE THREAD

**Issue by sloweia** [Tre5et/ridehud#4]
![2024-07-29_05 49 16](https://github.com/user-attachments/assets/28702e68-e7d6-4be6-8a05-17fdcea53676)

**Comment by Tre5et** [comment]
Hi, thanks for reporting this. The jump and speed bars now change their position according to max player health and absorption amount in v1.3.4, which should fix this. Let me know if you have any further issues with this.
